import { mkdtemp, rm, writeFile, readFile, mkdir, symlink } from 'node:fs/promises';
import { existsSync, readFileSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { DistMatrix, DistBuildReport, SdVersionInfo, BuildDiagnostic } from '@tokenflow/shared';

const execFileP = promisify(execFile);

/**
 * Phase 4 (redesign) — Style Dictionary **v5** generator, version detection, and
 * test-build runner.
 *
 * Model: a source has named `variants` (mode segments, or theme files). A target
 * renders each source's variants with a per-source strategy (selectors / media /
 * files / single) + value map. We use SD only to resolve + transform tokens
 * (`getPlatformTokens`), then emit CSS/SCSS/TS/JSON ourselves so one file can
 * hold several selector / media blocks — exactly the real-world layouts.
 */

/** Re-export the matrix types so consumers can import from one place. */
export type { DistMatrix, MatrixSource, MatrixTarget, SdVersionInfo } from '@tokenflow/shared';

/** Detect the project's installed Style Dictionary major version. */
export function detectSdVersion(root: string): SdVersionInfo {
  const pkg = join(root, 'node_modules/style-dictionary/package.json');
  if (!existsSync(pkg)) return { installed: null, mode: 'none' };
  try {
    const v = JSON.parse(readFileSync(pkg, 'utf8')).version as string;
    const major = Number(v.split('.')[0]);
    return { installed: major, mode: major <= 3 ? 'v3' : 'v5' };
  } catch {
    return { installed: null, mode: 'none' };
  }
}

/**
 * Emit a self-contained Style Dictionary v5 ESM build script for the matrix.
 * The body is plain JS built by string concatenation (no nested template
 * literals) so it round-trips cleanly through this template string.
 */
export function generateV5Script(matrix: DistMatrix): string {
  const json = JSON.stringify(matrix, null, 2);
  const tsImport = matrix.tokensStudio
    ? "import { register } from '@tokens-studio/sd-transforms';\nregister(StyleDictionary);\n"
    : '';
  return [
    '// Generated by Token Flow Manager — Style Dictionary v5 build.',
    '// Self-contained: edit the MATRIX below or regenerate from the app.',
    "import StyleDictionary from 'style-dictionary';",
    "import { readFileSync, statSync, mkdirSync, writeFileSync } from 'node:fs';",
    "import { fileURLToPath } from 'node:url';",
    "import { dirname, isAbsolute, join } from 'node:path';",
    tsImport,
    'const MATRIX = ' + json + ';',
    '',
    "function findRoot(d) { let x = d; while (x !== dirname(x)) { try { readFileSync(join(x, 'package.json')); return x; } catch {} x = dirname(x); } return d; }",
    'const ROOT = findRoot(dirname(fileURLToPath(import.meta.url)));',
    "const SRC = MATRIX.sourceRoot && isAbsolute(MATRIX.sourceRoot) ? MATRIX.sourceRoot : join(ROOT, MATRIX.sourceRoot || '.');",
    'const read = (p) => JSON.parse(readFileSync(join(SRC, p), "utf8"));',
    "const HEADER = '/* Generated by Token Flow Manager \\u2014 do not edit. */\\n\\n';",
    '',
    'const report = { ok: true, outputs: [], diagnostics: [] };',
    'const note = (level, message, extra) => report.diagnostics.push(Object.assign({ level: level, message: message }, extra || {}));',
    '',
    'function topKeys(o) { return Object.keys(o).filter(function (k) { return k[0] !== "$"; }); }',
    'function modeNames(s) { return s.variants.filter(function (v) { return !v.file; }).map(function (v) { return v.name; }); }',
    'function fileVariants(s) { return s.variants.filter(function (v) { return v.file; }); }',
    'function isCssVars(f) { return f === "css/variables"; }',
    'function isCssFamily(f) { return f.indexOf("css") === 0 || f.indexOf("scss") === 0 || f.indexOf("less") === 0; }',
    'function isJs(f) { return f.indexOf("javascript") === 0 || f.indexOf("typescript") === 0; }',
    'function isJson(f) { return f.indexOf("json") === 0; }',
    'function camel(id) { return id.split(/[^a-zA-Z0-9]+/).map(function (p, i) { return i ? p.charAt(0).toUpperCase() + p.slice(1) : p; }).join("").replace(/[^a-zA-Z0-9_$]/g, "") || "tokens"; }',
    'function cap(s) { return s.charAt(0).toUpperCase() + s.slice(1); }',
    '',
    'function readMerged(swapId, swapFile) {',
    '  const out = {};',
    '  for (const s of MATRIX.sources) {',
    '    let files = s.files;',
    '    if (swapId && s.id === swapId && swapFile) files = [swapFile];',
    '    const merged = {};',
    '    for (const f of files) Object.assign(merged, read(f));',
    '    if (s.wrapUnder) out[s.wrapUnder] = Object.assign(out[s.wrapUnder] || {}, merged);',
    '    else Object.assign(out, merged);',
    '  }',
    '  return out;',
    '}',
    '',
    'function outputKeys(s) {',
    '  if (s.wrapUnder) return new Set([s.wrapUnder]);',
    '  const keys = new Set();',
    '  for (const f of s.files) for (const k of topKeys(read(f))) keys.add(k);',
    '  return keys;',
    '}',
    '',
    'function registerNameTransforms(modes) {',
    '  const drop = function (token) { return token.path.filter(function (p) { return modes.indexOf(p) < 0; }); };',
    '  StyleDictionary.hooks.transforms["tfm/kebab"] = { type: "name", transform: function (t) { return drop(t).join("-").toLowerCase(); } };',
    '  StyleDictionary.hooks.transforms["tfm/camel"] = { type: "name", transform: function (t) { const ps = drop(t); return ps.map(function (p, i) { return i ? p.charAt(0).toUpperCase() + p.slice(1) : p; }).join("").replace(/[^a-zA-Z0-9_$]/g, ""); } };',
    '}',
    '',
    'async function platformTokens(format, tokens, modes) {',
    '  registerNameTransforms(modes || []);',
    '  const css = isCssFamily(format);',
    '  const transforms = css ? ["attribute/cti", "tfm/kebab", "color/css"] : ["attribute/cti", "tfm/camel"];',
    '  const sd = new StyleDictionary({',
    '    tokens: tokens, usesDtcg: true,',
    '    log: { verbosity: "verbose", warnings: "warn", errors: { brokenReferences: "console" } },',
    '    platforms: { out: { transforms: transforms } },',
    '  });',
    '  await sd.hasInitialized;',
    '  const pt = await sd.getPlatformTokens("out");',
    '  return pt.allTokens.map(function (t) { return { name: t.name, value: t.$value !== undefined ? t.$value : t.value, path: t.path }; });',
    '}',
    '',
    'function valOf(t) { return typeof t.value === "object" ? JSON.stringify(t.value) : String(t.value); }',
    'function cssVarLines(prefix, toks) { return toks.map(function (t) { return "  --" + prefix + t.name + ": " + valOf(t) + ";"; }).join("\\n"); }',
    'function scssVarLines(prefix, toks) { return toks.map(function (t) { return "$" + prefix + t.name + ": " + valOf(t) + ";"; }).join("\\n"); }',
    'function block(sel, body) { return sel + " {\\n" + body + "\\n}\\n"; }',
    '',
    'function nestObject(toks, strip) {',
    '  const root = {};',
    '  for (const t of toks) {',
    '    const path = t.path.filter(function (p) { return strip.indexOf(p) < 0; });',
    '    let node = root;',
    '    for (let i = 0; i < path.length - 1; i++) { node[path[i]] = node[path[i]] || {}; node = node[path[i]]; }',
    '    node[path[path.length - 1]] = t.value;',
    '  }',
    '  return root;',
    '}',
    '',
    'function resolveRendering(target, s) {',
    '  const r = (target.rendering && target.rendering[s.id]) || {};',
    '  const modes = modeNames(s);',
    '  const css = isCssVars(target.format);',
    '  let strategy = r.strategy;',
    '  if (!strategy) {',
    '    if (fileVariants(s).length) strategy = "files";',
    '    else if (!modes.length) strategy = "single";',
    '    else if (!css) strategy = "single";',
    '    else if (modes.every(function (m) { return /light|dark|theme/i.test(m); })) strategy = "selectors";',
    '    else if (modes.some(function (m) { return /desktop|tablet|mobile|width|screen|^(xs|sm|md|lg|xl)$/i.test(m); })) strategy = "media";',
    '    else strategy = "files";',
    '  }',
    '  const map = Object.assign({}, r.map || {});',
    '  for (const m of modes) {',
    '    if (map[m] != null) continue;',
    '    if (strategy === "selectors") map[m] = /dark/i.test(m) ? "[data-theme=\\u0027dark\\u0027]" : ":root";',
    '    else if (strategy === "media") map[m] = /tablet/i.test(m) ? "(min-width: 1024px)" : /desktop/i.test(m) ? "(min-width: 1440px)" : "";',
    '  }',
    '  return { strategy: strategy, map: map };',
    '}',
    '',
    'function writeOut(target, filename, content) {',
    '  const dir = join(ROOT, target.destination).replace(/[\\\\/]+$/, "") + "/";',
    '  mkdirSync(dir, { recursive: true });',
    '  writeFileSync(join(dir, filename), content);',
    '  let bytes = 0; try { bytes = statSync(join(dir, filename)).size; } catch {}',
    '  report.outputs.push({ target: target.label, file: filename, bytes: bytes });',
    '}',
    '',
    'for (const target of MATRIX.targets) {',
    '  const srcIds = target.sources === "all" ? MATRIX.sources.map(function (s) { return s.id; }) : target.sources;',
    '  const prefix = target.prefix || "";',
    '  const fmt = target.format;',
    '  for (const s of MATRIX.sources) {',
    '    if (srcIds.indexOf(s.id) < 0) continue;',
    '    try {',
    '      const okeys = outputKeys(s);',
    '      const belongs = function (t) { return okeys.has(t.path[0]); };',
    '      const stripNs = s.wrapUnder ? [s.wrapUnder] : [];',
    '      const modes = modeNames(s);',
    '      const fvars = fileVariants(s);',
    '      const rr = resolveRendering(target, s);',
    '      const baseName = camel(s.id);',
    '',
    '      let base = []; const byVar = {}; const order = [];',
    '      if (fvars.length) {',
    '        for (const fv of fvars) { order.push(fv.name); byVar[fv.name] = (await platformTokens(fmt, readMerged(s.id, fv.file), [])).filter(belongs); }',
    '      } else if (modes.length) {',
    '        const toks = (await platformTokens(fmt, readMerged(), modes)).filter(belongs);',
    '        for (const t of toks) { const v = modes.filter(function (m) { return t.path.indexOf(m) >= 0; })[0]; if (v) { (byVar[v] = byVar[v] || []).push(t); if (order.indexOf(v) < 0) order.push(v); } else base.push(t); }',
    '      } else {',
    '        base = (await platformTokens(fmt, readMerged(), [])).filter(belongs);',
    '      }',
    '      const hasVariants = order.length > 0;',
    '',
    '      if (isCssVars(fmt)) {',
    '        if (!hasVariants || rr.strategy === "single") {',
    '          const all = base.concat(order.flatMap(function (v) { return byVar[v]; }));',
    '          writeOut(target, baseName + ".css", HEADER + block(":root", cssVarLines(prefix, all)));',
    '        } else if (rr.strategy === "files") {',
    '          for (const v of order) writeOut(target, baseName + "." + v + ".css", HEADER + block(":root", cssVarLines(prefix, base.concat(byVar[v]))));',
    '        } else if (rr.strategy === "media") {',
    '          let out = HEADER; if (base.length) out += block(":root", cssVarLines(prefix, base));',
    '          for (const v of order) { const cond = rr.map[v]; if (!cond) { out += block(":root", cssVarLines(prefix, byVar[v])); } else { out += "@media " + cond + " {\\n  :root {\\n" + cssVarLines(prefix, byVar[v]) + "\\n  }\\n}\\n"; } }',
    '          writeOut(target, baseName + ".css", out);',
    '        } else {',
    '          const bySel = {}; const selOrder = [];',
    '          const add = function (sel, toks) { if (!bySel[sel]) { bySel[sel] = []; selOrder.push(sel); } bySel[sel] = bySel[sel].concat(toks); };',
    '          if (base.length) add(":root", base);',
    '          for (const v of order) add(rr.map[v] || ":root", byVar[v]);',
    '          let out = HEADER; for (const sel of selOrder) out += block(sel, cssVarLines(prefix, bySel[sel]));',
    '          writeOut(target, baseName + ".css", out);',
    '        }',
    '      } else if (fmt.indexOf("scss") === 0) {',
    '        if (!hasVariants || rr.strategy === "single") writeOut(target, "_" + baseName + ".scss", HEADER + scssVarLines(prefix, base.concat(order.flatMap(function (v) { return byVar[v]; }))) + "\\n");',
    '        else for (const v of order) writeOut(target, "_" + baseName + "-" + v + ".scss", HEADER + scssVarLines(prefix, base.concat(byVar[v])) + "\\n");',
    '      } else if (isJs(fmt)) {',
    '        const strip = stripNs.concat(modes);',
    '        if (rr.strategy === "files" && hasVariants) {',
    '          for (const v of order) writeOut(target, baseName + "." + v + ".ts", "export const " + baseName + cap(camel(v)) + " = " + JSON.stringify(nestObject(base.concat(byVar[v]), strip), null, 2) + ";\\n");',
    '        } else {',
    '          const obj = nestObject(base, strip); for (const v of order) obj[v] = nestObject(byVar[v], strip);',
    '          writeOut(target, baseName + ".ts", "export const " + baseName + " = " + JSON.stringify(obj, null, 2) + ";\\n");',
    '        }',
    '      } else if (isJson(fmt)) {',
    '        const strip = stripNs.concat(modes);',
    '        const obj = nestObject(base, strip); for (const v of order) obj[v] = nestObject(byVar[v], strip);',
    '        writeOut(target, baseName + ".json", JSON.stringify(obj, null, 2) + "\\n");',
    '      } else {',
    '        note("warn", "Unsupported format \\u2018" + fmt + "\\u2019 for " + s.id, { target: target.label });',
    '      }',
    '    } catch (err) {',
    '      report.ok = false;',
    '      note("error", String((err && err.message) || err), { target: target.label });',
    '    }',
    '  }',
    '}',
    '',
    "console.log('@@TFM_REPORT@@' + JSON.stringify(report));",
    '',
  ].join('\n');
}

/** Absolute path of a node_modules dir that resolves `style-dictionary` (v5). */
function styleDictionaryNodeModules(): string | null {
  try {
    // Resolve the package entry (its `exports` blocks `./package.json`), then take
    // the innermost `node_modules` ancestor — under pnpm this is the `.pnpm`
    // store dir that also holds Style Dictionary's own dependencies.
    const entry = createRequire(import.meta.url).resolve('style-dictionary');
    const marker = '/node_modules/';
    const i = entry.lastIndexOf(marker);
    if (i < 0) return null;
    return entry.slice(0, i + marker.length - 1); // …/node_modules
  } catch {
    return null;
  }
}

/**
 * Run a **dry-run** of the matrix and return a concise report. The generated v5
 * script is executed in a throwaway sandbox (its own `node_modules` symlinked to
 * our Style Dictionary v5), reading the project's real token files (absolute
 * `sourceRoot`) and writing into the sandbox — the project is never touched.
 */
export async function runTestBuild(
  root: string,
  matrix: DistMatrix,
  startedAt: number,
): Promise<DistBuildReport> {
  const nm = styleDictionaryNodeModules();
  if (!nm) {
    return { ok: false, outputs: [], diagnostics: [], error: 'Style Dictionary v5 is not available to run the test build.' };
  }
  const sandbox = await mkdtemp(join(tmpdir(), 'tfm-dryrun-'));
  try {
    await symlink(nm, join(sandbox, 'node_modules'), 'dir').catch(() => {});
    await writeFile(join(sandbox, 'package.json'), JSON.stringify({ name: 'tfm-dryrun', type: 'module' }));

    // Read the real tokens (absolute sourceRoot); write outputs inside the sandbox.
    const absSourceRoot = isAbsolute(matrix.sourceRoot) ? matrix.sourceRoot : resolve(root, matrix.sourceRoot);
    const dryMatrix: DistMatrix = {
      ...matrix,
      sourceRoot: absSourceRoot,
      targets: matrix.targets.map((t) => ({ ...t, destination: join('build', t.id) })),
    };
    await mkdir(join(sandbox, 'build'), { recursive: true });
    await writeFile(join(sandbox, 'tokens.build.mjs'), generateV5Script(dryMatrix));

    let stdout = '';
    let stderr = '';
    try {
      const res = await execFileP('node', ['tokens.build.mjs'], { cwd: sandbox, timeout: 60_000, maxBuffer: 16 * 1024 * 1024 });
      stdout = res.stdout;
      stderr = res.stderr;
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string; message?: string };
      stdout = e.stdout ?? '';
      stderr = e.stderr ?? '';
      if (!stdout.includes('@@TFM_REPORT@@')) {
        return {
          ok: false,
          outputs: [],
          diagnostics: [{ level: 'error', message: tail(e.message ?? 'Build failed', 600) }],
          error: 'The build script crashed before producing a report.',
          durationMs: Date.now() - startedAt,
        };
      }
    }

    const report = parseReport(stdout, stderr);
    await attachOutputContents(report, sandbox, dryMatrix);
    return { ...report, durationMs: Date.now() - startedAt };
  } finally {
    await rm(sandbox, { recursive: true, force: true }).catch(() => {});
  }
}

/**
 * Read each produced file back from the sandbox and attach its text content to
 * the report so the client can offer per-type zip downloads. Outputs only carry
 * a target label + filename, so we locate each file under its target's
 * destination dir (`build/<id>`); unreadable files simply keep `content` unset.
 */
async function attachOutputContents(report: DistBuildReport, sandbox: string, dryMatrix: DistMatrix): Promise<void> {
  const used = new Set<number>();
  for (const t of dryMatrix.targets) {
    const dir = join(sandbox, t.destination);
    for (let i = 0; i < report.outputs.length; i++) {
      if (used.has(i)) continue;
      const o = report.outputs[i]!;
      if (o.target !== t.label) continue;
      try {
        o.content = await readFile(join(dir, o.file), 'utf8');
        used.add(i);
      } catch {
        /* leave content undefined — the file will just not be downloadable */
      }
    }
  }
}

/**
 * Extract the JSON report the generated script prints behind a sentinel, and
 * enrich it with the broken-reference / collision lines Style Dictionary logs to
 * the console (stdout + stderr). Broken references downgrade `ok` to false.
 */
function parseReport(stdout: string, stderr: string): DistBuildReport {
  const marker = stdout.lastIndexOf('@@TFM_REPORT@@');
  if (marker < 0) return { ok: false, outputs: [], diagnostics: [], error: 'No build report was produced.' };
  const json = stdout.slice(marker + '@@TFM_REPORT@@'.length).split('\n')[0]!;
  let base: { ok: boolean; outputs: DistBuildReport['outputs']; diagnostics: BuildDiagnostic[] };
  try {
    base = JSON.parse(json);
  } catch {
    return { ok: false, outputs: [], diagnostics: [], error: 'Could not parse the build report.' };
  }

  const scanned = scanConsoleDiagnostics(stdout + '\n' + stderr);
  const diagnostics = [...(base.diagnostics ?? []), ...scanned];
  const ok = base.ok && !diagnostics.some((d) => d.level === 'error');
  return { ok, outputs: base.outputs ?? [], diagnostics };
}

/**
 * Scan console output (stdout + stderr) for the broken-reference / collision /
 * warning lines Style Dictionary (and most token build tools) log, and turn them
 * into structured diagnostics. Shared by the sandboxed test-build and the real
 * external-command run.
 */
export function scanConsoleDiagnostics(output: string): BuildDiagnostic[] {
  const seen = new Set<string>();
  const scanned: BuildDiagnostic[] = [];
  for (const raw of output.split('\n')) {
    // Strip ANSI colour codes Style Dictionary emits in verbose mode.
    const l = raw.replace(/\[[0-9;]*m/g, '').replace(/@@TFM_REPORT@@.*/, '').trim();
    if (!l || seen.has(l)) continue;
    // Drop internal noise: sandbox paths and bare written-file lines.
    if (l.includes('tfm-dryrun-') || /^[⚠️✔︎•\s]*\/.*\.(css|scss|less|ts|js|json)$/.test(l)) continue;
    // Unresolved references are real errors; collisions / filtered refs are warnings.
    const isError = /reference doesn't exist|is not defined|broken reference|errored|error:/i.test(l);
    const isWarn = !isError && /warning|⚠|deprecat|token collision|filtered out token/i.test(l);
    if (!isError && !isWarn) continue;
    seen.add(l);
    scanned.push({ level: isError ? 'error' : 'warn', message: l.slice(0, 240) });
    if (scanned.length >= 30) break;
  }
  return scanned;
}

/**
 * Run the project's REAL build command (`cwd = root`) and map the result to a
 * `DistBuildReport`. ⚠️ Unlike `runTestBuild`, this is NOT sandboxed: it executes
 * the project's own build and WRITES its real outputs to disk. Callers must
 * surface this to the user (it's "run the build", not a dry-run).
 */
export async function runExternalCommand(
  root: string,
  command: string,
  startedAt: number,
): Promise<DistBuildReport> {
  const cmd = command.trim();
  if (!cmd) {
    return { ok: false, outputs: [], diagnostics: [], error: 'No build command was provided.' };
  }
  let stdout = '';
  let stderr = '';
  let crashed: string | null = null;
  try {
    const shell = process.platform === 'win32' ? 'cmd' : 'sh';
    const shellArgs = process.platform === 'win32' ? ['/c', cmd] : ['-c', cmd];
    const res = await execFileP(shell, shellArgs, { cwd: root, timeout: 120_000, maxBuffer: 16 * 1024 * 1024 });
    stdout = res.stdout;
    stderr = res.stderr;
  } catch (err) {
    const e = err as { stdout?: string; stderr?: string; message?: string; killed?: boolean };
    stdout = e.stdout ?? '';
    stderr = e.stderr ?? '';
    crashed = e.killed ? 'The build command timed out.' : tail(e.message ?? 'The build command failed.', 600);
  }

  const combined = stdout + '\n' + stderr;
  const diagnostics = scanConsoleDiagnostics(combined);
  if (crashed && !diagnostics.some((d) => d.level === 'error')) {
    diagnostics.unshift({ level: 'error', message: crashed });
  }
  const ok = !crashed && !diagnostics.some((d) => d.level === 'error');
  return {
    ok,
    outputs: scanProducedFiles(combined, root),
    diagnostics,
    durationMs: Date.now() - startedAt,
    ...(crashed && !ok ? { error: crashed } : {}),
  };
}

/**
 * Best-effort list of files the external build wrote, by scanning its console
 * output for path-like tokens that actually exist on disk (resolved against the
 * build cwd). Most token build tools (Style Dictionary included) log each
 * written file; we confirm on disk and stat its real size. Unknown — we can't be
 * exhaustive — but it turns the "0 files" blank into a useful list.
 */
function scanProducedFiles(output: string, cwd: string): DistBuildReport['outputs'] {
  const outputs: DistBuildReport['outputs'] = [];
  const seen = new Set<string>();
  // Capture path-ish tokens ending in a known generated-asset extension.
  const re = /[\w./@-]+\.(?:css|scss|less|sass|ts|js|cjs|mjs|json)/g;
  for (const raw of output.split('\n')) {
    const line = raw.replace(/\[[0-9;]*m/g, '');
    for (const match of line.match(re) ?? []) {
      const rel = match.replace(/^\.\//, '');
      // Skip obvious source/config noise so we list generated files, not inputs.
      if (/node_modules\//.test(rel)) continue;
      const abs = isAbsolute(rel) ? rel : resolve(cwd, rel);
      let size: number;
      try {
        const st = statSync(abs);
        if (!st.isFile()) continue;
        size = st.size;
      } catch {
        continue; // not a real file → not an output
      }
      const key = isAbsolute(rel) ? relative(cwd, abs) : rel;
      if (seen.has(key)) continue;
      seen.add(key);
      outputs.push({ target: 'build', file: key, bytes: size });
      if (outputs.length >= 200) return outputs;
    }
  }
  return outputs;
}

function tail(s: string, n: number): string {
  return s.length <= n ? s : '…' + s.slice(-n);
}
