import { mkdtemp, rm, writeFile, readFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { isAbsolute, join, resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { DistConfig, DistBuildReport, BuildDiagnostic } from '@tokenflow/shared';

const execFileP = promisify(execFile);

/**
 * Deterministic, Style-Dictionary-free resolver.
 *
 * Emits a self-contained ESM build script (`tokens.build.mjs`) whose output is
 * identical regardless of input topology (nested modes vs. one file per mode).
 * `collections` define tokens + mode topology/mapping; `outputs` each pick a
 * format + destination + collection subset, so the same tokens can emit as SCSS
 * AND TypeScript to different folders. CSS/SCSS keep cross-collection references
 * as `var(--…)`; TS/JSON inline the referenced literal value. No `style-dictionary`
 * dependency, so the test build runs the script directly (no node_modules symlink).
 */

/**
 * The runtime that ships inside the generated `tokens.build.mjs`. Written with
 * string concatenation only (no template literals / backticks / `${`), so it can
 * live verbatim inside a `String.raw` block and round-trips byte-for-byte.
 */
const RUNTIME = String.raw`
const ROOT = (function findRoot(d) {
  let x = d;
  while (x !== dirname(x)) { try { readFileSync(join(x, 'package.json')); return x; } catch {} x = dirname(x); }
  return d;
})(dirname(fileURLToPath(import.meta.url)));
const SRC = CONFIG.sourceRoot && isAbsolute(CONFIG.sourceRoot) ? CONFIG.sourceRoot : join(ROOT, CONFIG.sourceRoot || '.');
const HEADER = '/* Generated by Token Flow Manager. Do not edit (see scripts/tokens.build.mjs). */\n\n';
const read = (p) => JSON.parse(readFileSync(join(SRC, p), 'utf8'));

const report = { ok: true, outputs: [], diagnostics: [] };
const note = (level, message, extra) => report.diagnostics.push(Object.assign({ level: level, message: message }, extra || {}));

function kebab(parts) {
  return parts.filter(Boolean).join('-').toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}
function slug(id) {
  return String(id).replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();
}
function camel(id) {
  const p = String(id).split(/[^a-zA-Z0-9]+/).filter(Boolean);
  return p.map(function (s, i) { return i ? s.charAt(0).toUpperCase() + s.slice(1) : s.toLowerCase(); }).join('') || 'tokens';
}

function leaves(obj, path, file, out) {
  if (!obj || typeof obj !== 'object') return;
  if ('$value' in obj) { out.push({ path: path, value: obj.$value, type: obj.$type || null, file: file }); return; }
  for (const k of Object.keys(obj)) { if (k.charAt(0) === '$') continue; leaves(obj[k], path.concat(k), file, out); }
}

const leavesByCol = {};
for (const c of CONFIG.collections) { const all = []; for (const f of c.files || []) leaves(read(f), [], f, all); leavesByCol[c.id] = all; }

function nestedStrip(col) {
  const s = new Set();
  for (const a of col.modeAxes) { if (a.source !== 'nested') continue; for (const k of Object.keys(a.map || {})) s.add(k); if (a.default) s.add(a.default); }
  return s;
}
function varName(col, path, strip) {
  const body = path.filter(function (p) { return !strip.has(p); });
  if (col.preserveCase) return [col.prefix, body[body.length - 1] || ''].filter(Boolean).join('-');
  return kebab([col.prefix].concat(body));
}
function modeOnAxis(axis, leaf) {
  if (axis.source === 'files') return (axis.fileMap || {})[leaf.file];
  const set = new Set(Object.keys(axis.map || {}));
  if (axis.default) set.add(axis.default);
  for (const p of leaf.path) if (set.has(p)) return p;
  return undefined;
}
function nonDefaultMode(col, leaf) {
  for (const a of col.modeAxes) { const m = modeOnAxis(a, leaf); if (m !== undefined && m !== a.default) return m; }
  return undefined;
}

// A collection is addressed in a {ref.path} by its prefix (if set) or, when the
// collection has no CSS namespace, by its kebab-cased id -- so refs resolve the
// same way whether or not the collection emits prefixed variable names.
function refKeys(c) {
  const keys = [];
  if (c.prefix) keys.push(c.prefix);
  const idKey = kebab([c.id]);
  if (idKey) keys.push(idKey);
  return keys.filter(function (k, i, arr) { return arr.indexOf(k) === i; });
}

const prefixById = {};
for (const c of CONFIG.collections) for (const k of refKeys(c)) prefixById[k] = c.prefix || '';

// --- CSS / SCSS reference resolution -> var(--…) (never inlined) ---
function resolveVar(value) {
  if (typeof value !== 'string') return value;
  return value.replace(/\{([^}]+)\}/g, function (_m, ref) {
    const segs = ref.split('.');
    const cid = segs[0];
    if (!(cid in prefixById)) { note('warn', 'Unresolved reference {' + ref + '}', { reference: ref }); return '/* unresolved: ' + ref + ' */'; }
    return 'var(--' + kebab([prefixById[cid]].concat(segs.slice(1))) + ')';
  });
}
function expandVar(col, name, value) {
  const v = resolveVar(value);
  if (v && typeof v === 'object' && !Array.isArray(v)) {
    const out = [];
    for (const k of Object.keys(v)) for (const p of expandVar(col, name + '-' + kebab([k]), v[k])) out.push(p);
    return out;
  }
  const s = Array.isArray(v) ? JSON.stringify(v) : String(v);
  return [{ name: name, value: col.preserveCase && s === '0px' ? '0' : s }];
}

// --- TS / JSON literal index + resolution (references inlined to values) ---
const lit = {};
for (const c of CONFIG.collections) {
  const strip = nestedStrip(c);
  const bucket = {};
  for (const l of leavesByCol[c.id]) {
    const key = kebab(l.path.filter(function (p) { return !strip.has(p); }));
    const mode = nonDefaultMode(c, l) || '__base__';
    (bucket[key] = bucket[key] || {})[mode] = l.value;
  }
  for (const k of refKeys(c)) lit[k] = bucket;
}
function lookupLit(ref, curMode) {
  const segs = ref.split('.');
  const e = lit[segs[0]] && lit[segs[0]][kebab(segs.slice(1))];
  if (!e) return undefined;
  if (curMode && e[curMode] !== undefined) return e[curMode];
  if (e['__base__'] !== undefined) return e['__base__'];
  const ks = Object.keys(e);
  return ks.length ? e[ks[0]] : undefined;
}
function resolveLiteral(value, curMode, seen) {
  if (typeof value !== 'string') return value;
  const whole = value.match(/^\s*\{([^}]+)\}\s*$/);
  if (whole) {
    const r = lookupLit(whole[1], curMode);
    if (r === undefined) { note('warn', 'Unresolved reference {' + whole[1] + '}', { reference: whole[1] }); return '/* unresolved: ' + whole[1] + ' */'; }
    if (typeof r === 'string' && /\{[^}]+\}/.test(r)) { const s = seen || new Set(); if (s.has(whole[1])) return r; s.add(whole[1]); return resolveLiteral(r, curMode, s); }
    return r;
  }
  if (/\{[^}]+\}/.test(value)) {
    return value.replace(/\{([^}]+)\}/g, function (_m, ref) {
      const r = lookupLit(ref, curMode);
      if (r === undefined) { note('warn', 'Unresolved reference {' + ref + '}', { reference: ref }); return '/* unresolved: ' + ref + ' */'; }
      return String(r);
    });
  }
  return value;
}

// --- Manifest (one entry per variable, deduped on modes) ---
function buildManifest() {
  const out = [];
  for (const col of CONFIG.collections) {
    const strip = nestedStrip(col);
    const byName = new Map();
    for (const l of leavesByCol[col.id]) {
      const name = varName(col, l.path, strip);
      let e = byName.get(name);
      if (!e) {
        const cat = l.path.filter(function (p) { return !strip.has(p); })[0] || col.id;
        e = { name: name, collection: col.id, category: cat, type: l.type || null, modes: [] };
        byName.set(name, e);
        out.push(e);
      }
      const mode = nonDefaultMode(col, l);
      if (mode && e.modes.indexOf(mode) < 0) e.modes.push(mode);
    }
  }
  return out;
}

// --- Per-format emitters: return [{ name, content, scss }] ---
function buildScssVars(col, strip) {
  const lines = [];
  const used = new Set();
  for (const l of leavesByCol[col.id]) {
    for (const p of expandVar(col, varName(col, l.path, strip), l.value)) {
      if (used.has(p.name)) continue;
      used.add(p.name);
      lines.push('$' + p.name + ': ' + p.value + ';');
    }
  }
  return [{ name: '_tokens-' + slug(col.id) + '.scss', content: HEADER + lines.join('\n') + '\n', scss: true }];
}

function buildCss(col, strip) {
  const filesAxis = col.modeAxes.find(function (a) { return a.strategy === 'files'; });
  if (filesAxis) {
    const def = filesAxis.default;
    const byMode = new Map();
    for (const l of leavesByCol[col.id]) { const m = modeOnAxis(filesAxis, l) || def; if (!byMode.has(m)) byMode.set(m, []); byMode.get(m).push(l); }
    const base = byMode.get(def) || [];
    const out = [];
    for (const [m, ls] of byMode) {
      const set = m === def ? base : base.concat(ls);
      const lines = [];
      for (const l of set) for (const p of expandVar(col, varName(col, l.path, strip), l.value)) lines.push('  --' + p.name + ': ' + p.value + ';');
      out.push({ name: '_tokens-' + slug(col.id) + (m === def ? '' : '-' + kebab([m])) + '.scss', content: HEADER + ':root {\n' + lines.join('\n') + '\n}\n', scss: true });
    }
    return out;
  }
  const groups = [];
  const byKey = new Map();
  function group(media, selector) {
    const key = media + '||' + selector;
    let g = byKey.get(key);
    if (!g) { g = { media: media, selector: selector, vars: new Map() }; byKey.set(key, g); groups.push(g); }
    return g;
  }
  for (const l of leavesByCol[col.id]) {
    const name = varName(col, l.path, strip);
    const selectorParts = [];
    const mediaParts = [];
    for (const a of col.modeAxes) {
      const m = modeOnAxis(a, l);
      if (m === undefined || m === a.default) continue;
      if (a.strategy === 'selectors') selectorParts.push((a.map || {})[m] || ':root');
      else if (a.strategy === 'media') { const cond = (a.map || {})[m]; if (cond) mediaParts.push(cond); }
    }
    const selector = selectorParts.length ? selectorParts.join('') : ':root';
    const media = mediaParts.length ? '@media ' + mediaParts.join(' and ') : '';
    const g = group(media, selector);
    for (const p of expandVar(col, name, l.value)) g.vars.set(p.name, p.value);
  }
  const rank = function (g) { return g.media ? 2 : g.selector === ':root' ? 0 : 1; };
  const ordered = groups.slice().sort(function (a, b) { return rank(a) - rank(b); });
  const linesOf = function (g) { const out = []; for (const [n, v] of g.vars) out.push('  --' + n + ': ' + v + ';'); return out.join('\n'); };
  let css = HEADER;
  for (const g of ordered) {
    if (g.media) css += g.media + ' {\n  ' + g.selector + ' {\n' + linesOf(g).replace(/^/gm, '  ') + '\n  }\n}\n';
    else css += g.selector + ' {\n' + linesOf(g) + '\n}\n';
  }
  return [{ name: '_tokens-' + slug(col.id) + '.scss', content: css, scss: true }];
}

function buildScssMixin(col, strip) {
  const selAxes = col.modeAxes.filter(function (a) { return a.strategy === 'selectors' || a.strategy === 'files'; });
  const isTheme = function (a) { return [a.default].concat(Object.keys(a.map || {})).some(function (m) { return /light|dark|day|night|contrast/i.test(m); }); };
  const themeAxis = selAxes.find(isTheme) || null;
  const brandAxis = selAxes.find(function (a) { return a !== themeAxis; }) || null;
  const modesOf = function (a) { const s = new Set(); if (a.default) s.add(a.default); for (const k of Object.keys(a.map || {})) s.add(k); if (a.fileMap) for (const v of Object.values(a.fileMap)) s.add(v); return [...s]; };
  const map = new Map();
  for (const l of leavesByCol[col.id]) {
    const b = brandAxis ? modeOnAxis(brandAxis, l) || brandAxis.default : 'default';
    const t = themeAxis ? modeOnAxis(themeAxis, l) || themeAxis.default : 'base';
    if (!map.has(b)) map.set(b, new Map());
    if (!map.get(b).has(t)) map.get(b).set(t, new Map());
    const vars = map.get(b).get(t);
    for (const p of expandVar(col, varName(col, l.path, strip), l.value)) vars.set(p.name, p.value);
  }
  const mapVar = '$' + (col.prefix ? col.prefix + '-' : '') + 'themes';
  const mixin = (col.prefix || 'theme') + '-apply';
  const defBrand = brandAxis ? brandAxis.default : 'default';
  const defTheme = themeAxis ? themeAxis.default : 'base';
  const selBlock = function (sel) { return '&' + sel + ', ' + sel + ' &'; };
  let out = HEADER + mapVar + ': (\n';
  for (const [b, tm] of map) {
    out += '  "' + b + '": (\n';
    for (const [t, vars] of tm) {
      out += '    "' + t + '": (\n';
      for (const [n, v] of vars) out += '      "' + n + '": ' + v + ',\n';
      out += '    ),\n';
    }
    out += '  ),\n';
  }
  out += ');\n\n@mixin ' + mixin + '($name) {\n  $m: map-get(' + mapVar + ', $name);\n  $base: map-get($m, "' + defTheme + '");\n  @if $base { @each $n, $v in $base { --#{$n}: #{$v}; } }\n';
  if (themeAxis) {
    for (const t of modesOf(themeAxis)) {
      if (t === defTheme) continue;
      out += '  $' + slug(t) + ': map-get($m, "' + t + '");\n  @if $' + slug(t) + ' and length($' + slug(t) + ') > 0 {\n    ' + selBlock((themeAxis.map || {})[t] || '.' + slug(t)) + ' {\n      @each $n, $v in $' + slug(t) + ' { --#{$n}: #{$v}; }\n    }\n  }\n';
    }
  }
  out += '}\n\n:root {\n  @include ' + mixin + '("' + defBrand + '");\n}\n\n@each $name, $cfg in ' + mapVar + ' {\n  ._#{to-lower-case($name)} {\n    @include ' + mixin + '($name);\n  }\n}\n';
  return [{ name: '_tokens-' + slug(col.id) + '.scss', content: out, scss: true }];
}

function buildNested(col, strip) {
  const root = {};
  for (const l of leavesByCol[col.id]) {
    const modeKeys = [];
    for (const a of col.modeAxes) { const m = modeOnAxis(a, l); if (m !== undefined && m !== a.default) modeKeys.push(m); }
    const body = l.path.filter(function (p) { return !strip.has(p); });
    const val = resolveLiteral(l.value, modeKeys[0]);
    const path = modeKeys.concat(body);
    let node = root;
    for (let i = 0; i < path.length - 1; i++) { const k = path[i]; if (typeof node[k] !== 'object' || node[k] === null) node[k] = {}; node = node[k]; }
    node[path[path.length - 1]] = val;
  }
  return root;
}

function buildFiles(col, format) {
  const strip = nestedStrip(col);
  if (format === 'scss-vars') return buildScssVars(col, strip);
  if (format === 'scss-mixin') return buildScssMixin(col, strip);
  if (format === 'ts') return [{ name: slug(col.id) + '.ts', content: 'export const ' + camel(col.prefix || col.id) + ' = ' + JSON.stringify(buildNested(col, strip), null, 2) + ' as const;\n', scss: false }];
  if (format === 'json') return [{ name: slug(col.id) + '.json', content: JSON.stringify(buildNested(col, strip), null, 2) + '\n', scss: false }];
  return buildCss(col, strip);
}

// --- Driver: emit every output (format × destination × collections) ---
const allIds = CONFIG.collections.map(function (c) { return c.id; });
const partialsByDest = {};
function emit(destRel, name, content, scss, fmt) {
  const dir = isAbsolute(destRel) ? destRel : join(ROOT, destRel || '.');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, name), content);
  let bytes = 0; try { bytes = Buffer.byteLength(content); } catch {}
  report.outputs.push({ target: fmt, file: (destRel ? destRel + '/' : '') + name, bytes: bytes });
  if (scss) (partialsByDest[destRel] = partialsByDest[destRel] || []).push(name);
}

for (const output of CONFIG.outputs || []) {
  const ids = output.collections === 'all' ? allIds : (output.collections || []);
  for (const col of CONFIG.collections) {
    if (ids.indexOf(col.id) < 0) continue;
    try { for (const f of buildFiles(col, output.format)) emit(output.destination, f.name, f.content, f.scss, output.format); }
    catch (err) { report.ok = false; note('error', String((err && err.message) || err), { target: col.id }); }
  }
}

// Per-destination SCSS index (@use each partial once) + manifest.
const manifestContent = JSON.stringify({ tokens: buildManifest() }, null, 2) + '\n';
const seenDest = new Set();
for (const output of CONFIG.outputs || []) {
  const destRel = output.destination;
  if (seenDest.has(destRel)) continue;
  seenDest.add(destRel);
  const dir = isAbsolute(destRel) ? destRel : join(ROOT, destRel || '.');
  const partials = partialsByDest[destRel] || [];
  if (partials.length) {
    const index = HEADER + partials.map(function (f) { return "@use './" + f.replace(/^_/, '').replace(/\.scss$/, '') + "';"; }).join('\n') + '\n';
    writeFileSync(join(dir, '_tokens.scss'), index);
    report.outputs.push({ target: 'index', file: (destRel ? destRel + '/' : '') + '_tokens.scss', bytes: Buffer.byteLength(index) });
  }
  if (CONFIG.manifest) {
    writeFileSync(join(dir, 'tokens.manifest.json'), manifestContent);
    report.outputs.push({ target: 'manifest', file: (destRel ? destRel + '/' : '') + 'tokens.manifest.json', bytes: Buffer.byteLength(manifestContent) });
  }
}

if (report.diagnostics.some(function (d) { return d.level === 'error'; })) report.ok = false;
console.log('@@TFM_REPORT@@' + JSON.stringify(report));
`;

/** Emit a self-contained, SD-free deterministic build script for the config. */
export function generateResolverScript(config: DistConfig): string {
  return [
    '// Generated by Token Flow Manager — deterministic resolver build.',
    '// Self-contained: edit the CONFIG below or regenerate from the app.',
    "import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';",
    "import { fileURLToPath } from 'node:url';",
    "import { dirname, isAbsolute, join } from 'node:path';",
    '',
    'const CONFIG = ' + JSON.stringify(config, null, 2) + ';',
    RUNTIME,
  ].join('\n');
}

/**
 * Dry-run the build in a throwaway sandbox: write the generated script, run it
 * with the project's real tokens (absolute `sourceRoot`) writing into the
 * sandbox, then read the produced files back so the UI can preview / download
 * them. The project is never touched, and no Style Dictionary is needed.
 */
export async function runResolverBuild(root: string, config: DistConfig, startedAt: number): Promise<DistBuildReport> {
  const sandbox = await mkdtemp(join(tmpdir(), 'tfm-resolve-'));
  try {
    const absSourceRoot = isAbsolute(config.sourceRoot) ? config.sourceRoot : resolve(root, config.sourceRoot || '.');
    // Keep destinations relative so they land inside the sandbox (ROOT = sandbox).
    const dryConfig: DistConfig = {
      ...config,
      sourceRoot: absSourceRoot,
      outputs: config.outputs.map((o) => ({ ...o, destination: o.destination.replace(/^([a-zA-Z]:)?[\\/]+/, '') })),
    };
    await writeFile(join(sandbox, 'package.json'), JSON.stringify({ name: 'tfm-resolve', type: 'module' }));
    await writeFile(join(sandbox, 'tokens.build.mjs'), generateResolverScript(dryConfig));

    let stdout = '';
    try {
      const res = await execFileP('node', ['tokens.build.mjs'], { cwd: sandbox, timeout: 60_000, maxBuffer: 16 * 1024 * 1024 });
      stdout = res.stdout;
    } catch (err) {
      const e = err as { stdout?: string; message?: string };
      stdout = e.stdout ?? '';
      if (!stdout.includes('@@TFM_REPORT@@')) {
        return {
          ok: false,
          outputs: [],
          diagnostics: [{ level: 'error', message: (e.message ?? 'Build failed').slice(-600) }],
          error: 'The build script crashed before producing a report.',
          durationMs: Date.now() - startedAt,
        };
      }
    }

    const report = parseReport(stdout);
    for (const o of report.outputs) {
      try {
        o.content = await readFile(join(sandbox, o.file), 'utf8');
      } catch {
        /* leave content unset — file just not downloadable */
      }
    }
    return { ...report, durationMs: Date.now() - startedAt };
  } finally {
    await rm(sandbox, { recursive: true, force: true }).catch(() => {});
  }
}

/** Parse the `@@TFM_REPORT@@`-sentinel JSON the generated script prints. */
function parseReport(stdout: string): DistBuildReport {
  const marker = stdout.lastIndexOf('@@TFM_REPORT@@');
  if (marker < 0) return { ok: false, outputs: [], diagnostics: [], error: 'No build report was produced.' };
  const json = stdout.slice(marker + '@@TFM_REPORT@@'.length).split('\n')[0]!;
  try {
    const base = JSON.parse(json) as { ok: boolean; outputs: DistBuildReport['outputs']; diagnostics: BuildDiagnostic[] };
    const ok = base.ok && !base.diagnostics.some((d) => d.level === 'error');
    return { ok, outputs: base.outputs ?? [], diagnostics: base.diagnostics ?? [] };
  } catch {
    return { ok: false, outputs: [], diagnostics: [], error: 'Could not parse the build report.' };
  }
}
