import { z } from 'zod';

export const CollectionConfigSchema = z.object({
  name: z.string(),
  /** Glob (or array of globs) of files belonging to this collection. */
  files: z.union([z.string(), z.array(z.string())]),
  /** Declared modes; if omitted, inferred from inline values / a mode dimension. */
  modes: z.array(z.string()).optional(),
  /** Path depth whose segment encodes the mode (Tokens-Studio / PrimeNG style). */
  modeDimension: z.number().int().nonnegative().optional(),
  /** Map of relative file path → mode (file-based modes, e.g. one file per theme). */
  fileModes: z.record(z.string()).optional(),
  /**
   * Map of internal mode id (physical path segment, e.g. `modeLight`) → display
   * name from the organization manifest (e.g. `Light`). In-memory only — derived
   * from `manifest.json` at load and emitted back to it; never written to
   * `tokenflow.config.json` (which holds tool preferences only).
   */
  modeLabels: z.record(z.string()).optional(),
});
export type CollectionConfig = z.infer<typeof CollectionConfigSchema>;

export const ResolutionConfigSchema = z.object({
  /** Allow aliases to cross collection boundaries. */
  crossCollection: z.boolean().default(true),
  /** Resolution order; a collection may only reference those before it. */
  order: z.array(z.string()).optional(),
  /** Max alias chain depth before a warning is raised. */
  maxAliasDepth: z.number().int().positive().default(10),
});
export type ResolutionConfig = z.infer<typeof ResolutionConfigSchema>;

export const TokenflowConfigSchema = z.object({
  collections: z.array(CollectionConfigSchema).min(1),
  resolution: ResolutionConfigSchema.default({
    crossCollection: true,
    maxAliasDepth: 10,
  }),
  /** Debounce window (ms) before reloading after an external file change. */
  writeDebounceMs: z.number().int().nonnegative().default(200),
  /** Emit errors for tokens with a missing/unknown `$type`. Off = tolerant. */
  strictTypes: z.boolean().default(false),
  /** Infer a token's type from its value when `$type` is absent/unknown. */
  inferTypes: z.boolean().default(true),
  /**
   * Marks a config written by the tool itself (settings persistence). Such
   * configs persist only settings — collections are re-detected on each load so
   * a manifest or newly-added files always take effect.
   */
  autoGenerated: z.boolean().optional(),
});
export type TokenflowConfig = z.infer<typeof TokenflowConfigSchema>;

/**
 * Zero-config default: treat any `*.tokens.json` as a single "Tokens" collection.
 */
export const DEFAULT_CONFIG: TokenflowConfig = {
  collections: [{ name: 'Tokens', files: '**/*.json' }],
  resolution: { crossCollection: true, maxAliasDepth: 10 },
  writeDebounceMs: 200,
  strictTypes: false,
  inferTypes: true,
};

export function defineConfig(config: TokenflowConfig): TokenflowConfig {
  return config;
}
